In [ ]:
# скачиваем файл
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1VPkoWfiIvZl4HGp49BUaVEEblVIGYh91' -O heart.csv

--2021-11-05 21:09:35--  https://docs.google.com/uc?export=download&id=1VPkoWfiIvZl4HGp49BUaVEEblVIGYh91
Resolving docs.google.com (docs.google.com)... 172.217.9.206, 2607:f8b0:4004:806::200e
Connecting to docs.google.com (docs.google.com)|172.217.9.206|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://doc-0k-5k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/gngh74jh69cqu8fh5svmaqon1gj7rpa1/1636146525000/07828702499945486090/*/1VPkoWfiIvZl4HGp49BUaVEEblVIGYh91?e=download [following]
--2021-11-05 21:09:35--  https://doc-0k-5k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/gngh74jh69cqu8fh5svmaqon1gj7rpa1/1636146525000/07828702499945486090/*/1VPkoWfiIvZl4HGp49BUaVEEblVIGYh91?e=download
Resolving doc-0k-5k-docs.googleusercontent.com (doc-0k-5k-docs.googleusercontent.com)... 142.251.33.193, 2607:f8b0:4004:837::2001
Connecting to doc-0k-5k-docs.googleusercontent.com (doc-0k-5k-docs.googleu

In [ ]:
# устанавливаем нужную версию библиотеки sklearn, чтобы ответы сошлись
!pip install scikit-learn==0.22.1

     |████████████████████████████████| 7.0 MB 26.6 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [ ]:
import numpy as np
import pandas as pd

В этом задании вы будете работать с [данными о пациентах, у части которых есть заболевание сердца](https://www.kaggle.com/ronitf/heart-disease-uci). Вам нужно построить модель, классифицирующую пациентов на больных этим заболеванием и тех, у кого его нет, а также проанализировать результаты.

In [ ]:
data = pd.read_csv('heart.csv')
data.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

1. Какой процент пациентов из представленных в данных имеет заболевание сердца (`'target' = 1`)? Ответ округлите до двух знаков после запятой.

In [ ]:
data.target.value_counts(normalize=True)

1    0.544554
0    0.455446
Name: target, dtype: float64

**Ответ:** 54,46% пациентов в выборке имеет заболевание сердца:

Разделим данную выборку на обучающую и тестовую части в отношении 3:1.

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.drop('target', axis=1), data['target'], test_size=0.25, random_state=13)
X_train.shape, X_test.shape

((227, 13), (76, 13))

2. Обучите линейный классификатор из `sklearn` (`sklearn.linear_model.SGDClassifier`) с максимальным числом итераций `max_iter=1000`, постоянным значением шага градиентного спуска (`learning_rate='constant'`), равным `eta0=0.1`. В качестве сида поставьте `random_state=13`. Параметр регуляризации отключите: `alpha=0`. Класс `sklearn.linear_model.SGDClassifier` объединяет в себе разные линейные модели - чтобы получить логистическую регрессию, зафиксируйте параметр `loss='log'`.

   Подробнее о параметрах можно почитать в [документации](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html).

   Какое значение свободного коэффициента у полученного линейного классификатора? Ответ округлите до двух знаков после запятой.

In [ ]:
from sklearn.linear_model import SGDClassifier

clf = SGDClassifier(max_iter=1000, learning_rate='constant', eta0=0.1, random_state=13, alpha=0, loss='log')

In [ ]:
clf.fit(X_train, y_train)

SGDClassifier(alpha=0, average=False, class_weight=None, early_stopping=False,
              epsilon=0.1, eta0=0.1, fit_intercept=True, l1_ratio=0.15,
              learning_rate='constant', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=13, shuffle=True, tol=0.001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [ ]:
clf.intercept_  # возвращает свободный коэффициент

array([-1.15927929])

3. Какое значение L2-нормы вектора весов (без учета свободного коэффициента) у полученного линейного классификатора? Ответ округлите до двух знаков после запятой.

_Напоминание. L2-норма вектора $v = (v_1, \ldots, v_n)$ - это корень из суммы квадратов его элементов:_

$$
\|v\|_2 = \sqrt{\sum\limits_{i=1}^nv_i^2}
$$

In [ ]:
w = clf.coef_
sqrt_w = pow(w, 2)
sum = sqrt_w.sum()
l2_norm = sum ** 0.5

print(l2_norm)

175.67735435821564


4. Найдите долю правильных ответов классификатора на тестовой части выборки **(в процентах)**. Ответ округлите до двух знаков после запятой. Например, если значение доли правильных ответов будет равно 0.1234, то ответом будет 12.34 - ведь это 12.34%.

In [ ]:
import numpy as np

y_test_predict = clf.predict(X_test)
y_test_comp = np.equal(y_test_predict, y_test)
y_test_comp.value_counts(normalize=True)

True     0.618421
False    0.381579
Name: target, dtype: float64

**Ответ:** Доля правильных ответов на тестовой выборке - 61,84%.

5. В задаче классификации, как и в задаче регрессии, для оптимизации линейных моделей можно применять регуляризацию. Этот метод реализован и в `sklearn.linear_model.SGDClassifier` - параметр регуляризации обозначается параметром `alpha`. За тип регуляризации (L1, L2 или обе сразу) отвечает параметр `penalty`. 

   Обучите классификатор заново с параметром регуляризации `alpha=0.1` и типом регуляризации `penalty='l1'`. Оставьте максимальное число итераций, равное `max_iter=1000` и сид `random_state=13`. Также вместо постоянного значения шага градиентного спуска используйте оптимальное (`learning_rate='optimal'`), которое, кстати, зависит от `alpha` (о том, как именно он вычисляется и какие еще параметры можно выбрать, можно подробнее прочитать в [документации](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html)). В данном случае значение начального шага градиентного спуска `eta0` никак не участвует в обучении.
   
   Отличается ли качество полученного классификатора от качества первого? Какая доля правильных ответов получается теперь на тестовой выборке? Выразите ее **в процентах**, ответ округлите до двух знаков после запятой. Например, если значение доли правильных ответов будет равно 0.1234, то ответом будет 12.34 - ведь это 12.34%.

In [ ]:
clf_reg = SGDClassifier(max_iter=1000, 
                        learning_rate='optimal', 
                        eta0=0.1,
                        random_state=13,
                        alpha=0.1,
                        loss='log',
                        penalty='l1')

clf_reg.fit(X_train, y_train)

SGDClassifier(alpha=0.1, average=False, class_weight=None, early_stopping=False,
              epsilon=0.1, eta0=0.1, fit_intercept=True, l1_ratio=0.15,
              learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l1', power_t=0.5,
              random_state=13, shuffle=True, tol=0.001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [ ]:
import numpy as np

y_test_reg_predict = clf_reg.predict(X_test)
y_test_reg_comp = np.equal(y_test_reg_predict, y_test)
y_test_reg_comp.value_counts(normalize=True)

True     0.763158
False    0.236842
Name: target, dtype: float64

Ответ: при использовании регуляризации был улучшено предсказание модели на тестовой выборке - 76,32%.

6. Найдите L2-норму вектора весов для полученного классификатора (заметьте, как на нее повлияла регуляризация). Ответ округлите до двух знаков после запятой.

    Заметьте, что вектор стал более разреженным, и в нем появились нулевые элементы - это результат действия L1-регуляризации.

In [ ]:
w_reg = clf_reg.coef_
w_reg     # вывод весовых коэффициентов.

array([[-0.87424016,  0.        ,  9.26085004, -0.45773776, -0.01501012,
         0.        ,  0.        ,  0.74467772,  0.        , -0.25903021,
         0.        , -4.1192229 , -2.1071261 ]])

In [ ]:
from numpy.linalg import norm

norm(w_reg)   # выводит номру вектора (используется билблиотека numpy).

10.429142228977849

7. Наконец, проверьте, как полученные классификаторы предсказывают не классы, а вероятности классов - так как мы работаем с логистической регрессией, это можно сделать. Посмотрите на вероятности, которые выдает первый классификатор (обученный с постоянным шагом градиентного спуска и без регуляризации) на тестовой части выборки. В этом вам поможет метод `predict_proba`. Результатом его работы будет список размера $N\times 2$, где $N$ - это число объектов. В каждом столбце списка находятся вероятности соответствующего класса для объектов. Поэтому если вам нужен положительный класс, вас интересует последний столбец.

    Какое получается значение AUC-ROC? Ответ округлите до двух знаков после запятой.

In [ ]:
clf_reg.predict_proba(X_train)

array([[0.00000000e+00, 1.00000000e+00],
       [2.67431781e-01, 7.32568219e-01],
       [9.99839412e-01, 1.60587526e-04],
       [9.99999997e-01, 3.14574079e-09],
       [1.47832493e-02, 9.85216751e-01],
       [1.05337761e-06, 9.99998947e-01],
       [4.62322374e-07, 9.99999538e-01],
       [4.97896044e-06, 9.99995021e-01],
       [2.66095157e-04, 9.99733905e-01],
       [9.99914051e-01, 8.59488950e-05],
       [2.75741652e-11, 1.00000000e+00],
       [1.11022302e-15, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [9.99999254e-01, 7.46037595e-07],
       [1.00000000e+00, 2.17252532e-17],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 3.60766635e-15],
       [9.96765729e-01, 3.23427112e-03],
       [1.00000000e+00, 1.64018873e-10],
       [7.17213587e-07, 9.99999283e-01],
       [1.45309177e-05, 9.99985469e-01],
       [1.00000000e+00, 9.47934143e-13],
       [1.00000000e+00, 1.65513982e-11],
       [1.27683061e-05, 9.99987232e-01],
       [1.000000

In [ ]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, clf.predict_proba(X_test)[:, 1])  # Вывод значения метрики AUC-ROC для первого классификатора.

0.5697674418604651

8. Посмотрите на вероятности, которые выдает второй классификатор (обученный с оптимальным шагом градиентного спуска и с регуляризацией) на тестовой части выборки. Что вы наблюдаете - как отличаются эти вероятности от вероятностей первого классификатора?

   Посчитайте значение AUC-ROC второго классификатора. Ответ округлите до двух знаков после запятой.

In [ ]:
roc_auc_score(y_test, clf_reg.predict_proba(X_test)[:, 1])  # Вывод значения метрики AUC-ROC для второго классификатора.

0.8558844256518675

9. Какой признак является самым важным по мнению лучшей модели (имеет наибольший по модулю коэффициент) для принятия решения?

In [ ]:
max_id = np.argmax(clf_reg.coef_)
max_val = clf_reg.coef_[0, max_id]

print("Максимальный коэффициент = %.2f" % max_val)
print("Индекс максимального коэффициента = %i" % max_id)

Максимальный коэффициент = 9.26
Индекс максимального коэффициента = 2
