### Логистическая регрессия

1. Загрузите данные `load_wine` из `sklearn.datasets`. Из данных исключите объекты класса 2.
 Отмасштабируйте признаки, используя класс `StandardScaler` с гиперпараметрами по умолчанию. Обучите логистическую регрессию и оцените важность признаков. Укажите название признака, который оказался наименее значимым.

Обратите внимание, целевое значение лежит по ключу `'target'`, матрица объекты-признаки лежит по ключу `'data'`



In [ ]:
from sklearn.datasets import load_wine
data = load_wine()
print(data)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X = data.data
Y = data.target

In [ ]:
scaler = StandardScaler()
X_prep = scaler.fit_transform(X)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
clf = LogisticRegression(random_state=0, max_iter=10000).fit(X_prep, Y)

In [ ]:
clf.coef_.argmin(axis=1)

array([ 3, 12,  6])

In [ ]:
max_name = data.feature_names[clf.coef_.argmax()]
min_name = data.feature_names[clf.coef_.argmin()]

print("Признак %s - наиболее значимый." % max_name)
print("Признак %s - наименее значимый." % min_name)

IndexError: ignored

In [ ]:
clf.coef_.shape   # Почему размерность = (3, 13)? (Ожидалось (1, 13))

(3, 13)

In [ ]:
clf.coef_

array([[ 0.81013479,  0.20382073,  0.47221242, -0.84478439,  0.04952905,
         0.2137248 ,  0.64787507, -0.19982499,  0.13833868,  0.17160966,
         0.13090887,  0.72595069,  1.07895949],
       [-1.01032338, -0.44045953, -0.848074  ,  0.58357323, -0.09770602,
         0.02752798,  0.35399157,  0.21278279,  0.26336105, -1.04127077,
         0.6825216 ,  0.05287635, -1.14079293],
       [ 0.20018858,  0.2366388 ,  0.37586158,  0.26121116,  0.04817698,
        -0.24125278, -1.00186664, -0.0129578 , -0.40169973,  0.86966111,
        -0.81343047, -0.77882704,  0.06183345]])

2. Загрузите данные `load_wine` из `sklearn.datasets`. Из обучающей части исключите объекты соответствующие классу 2. Не масштабируйте признаки. Обучите логистическую регрессию с гиперпараметрами по умолчанию.
Выберите признак из предложенных, которому соответствует минимальный вес. 


In [ ]:
import numpy as np

In [ ]:
X2 = X[np.where(data.target == 2, False, True)]
Y2 = Y[np.where(data.target == 2, False, True)]

In [ ]:
clf2 = LogisticRegression(random_state=0, max_iter=1000000).fit(X2, Y2)

In [ ]:
clf2.coef_.shape    # Почему здесь размерность уже (1, 13)?

(1, 13)

In [ ]:
min_id_2 = clf2.coef_.argmin()
min_val_2 = clf2.coef_.min()
min_name_2 = data.feature_names[min_id_2]

print("Признак %s - наименее значимый." % min_name_2)

Признак malic_acid - наименее значимый.


In [ ]:
clf2.coef_

array([[-1.02410929, -1.14093323, -0.88024923,  0.28030539,  0.01397401,
        -0.06454458, -0.50326359, -0.14500409,  0.15385107, -0.94058169,
         0.12151031, -0.52160009, -0.01659872]])

In [ ]:
data.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

3. Решается задача бинарной классификации. Дана матрица объекты признаки 𝑋 и ответы для объектов  𝑦. Обучите логистическую регрессию и предскажите класс объекта x_new

In [ ]:
X = np.array([[1, 1], [0.3, 0.7], [0, 4], [-2, -7], [0, -2], [-1, -1], [-2, 0]])
y = np.array([1, 1, 1, 0, 0, 0, 0])
x_new = np.array([[-5, 1]])

In [ ]:
clf3 = LogisticRegression().fit(X, y)
clf3.predict(x_new)

array([0])

### Классификация текстов

4. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer` с гиперпараметрами по умолчанию на текстах из обучающей части и получите векторное представление для объектов обучающей и тестовой части. Укажите полученное число признаков.


Чтобы загрузить данные, скачайте файл по ссылке. Если вы используете google colab, то пример загрузки данных приведен ниже.

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
sms_data = pd.read_csv('SMSSpamCollection', sep='\t',# quoting=csv.QUOTE_NONE,
                           names=["label", "message"])
sms_data

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
sms_train = sms_data[:4000]
sms_test = sms_data[4000:]

In [ ]:
vectorizer = TfidfVectorizer()

In [ ]:
bow_train = vectorizer.fit_transform(sms_train.message)
bow_test = vectorizer.transform(sms_test.message)

In [ ]:
print("Количество признаков = %i" %len(vectorizer.get_feature_names()))

Количество признаков = 7331


5.  Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer`, помимо слов входящих в тексты, учитывайте биграммы (используйте гиперпараметр `ngram_range`). Укажите полученное число признаков.

In [ ]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2))
bow_train = vectorizer.fit_transform(sms_train.message)
bow_test = vectorizer.transform(sms_test.message)
print("Количество признаков = %i" %len(vectorizer.get_feature_names()))

Количество признаков = 39805


6. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer`, не учитывайте слова, которые встретились меньше 2 раз в обучающей выборке (используйте гиперпараметр `min_df`). Укажите полученное число признаков.

In [ ]:
vectorizer = TfidfVectorizer(min_df=2)
bow_train = vectorizer.fit_transform(sms_train.message)
bow_test = vectorizer.transform(sms_test.message)
print("Количество признаков = %i" %len(vectorizer.get_feature_names()))

Количество признаков = 3377


7. Загрузите файл SMSSpamCollection из UCI (https://archive.ics.uci.edu/ml/machine-learning-databases/00228/). Данные содержат текстовую информацию и бинарное целевое значение (‘spam’, ‘ham’), Пусть в обучающую часть попадут первые 4000 объектов из таблицы, в тестовую часть оставшиеся объекты. Обучите `TfidfVectorizer` с гиперпараметрами по умолчанию на текстах из обучающей части и получите векторное представление для объектов обучающей и тестовой части. На полученных векторных представлениях обучите логистическую регрессию и оцените долю правильных ответов на тестовой части. Укажите полученное значение доли правильных ответов.

In [ ]:
vectorizer = TfidfVectorizer()
bow_train = vectorizer.fit_transform(sms_train.message)
bow_test = vectorizer.transform(sms_test.message)
print("Количество признаков = %i" %len(vectorizer.get_feature_names()))

Количество признаков = 7331


In [ ]:
y_train = sms_train.label.replace("ham", 0).replace("spam", 1)
y_test = sms_test.label.replace("ham", 0).replace("spam", 1)

In [ ]:
clf = LogisticRegression()
clf = clf.fit(bow_train, y_train)

In [ ]:
y_test_predict = clf.predict(bow_test)
np.equal(y_test_predict, y_test).value_counts(normalize=True)

True     0.969466
False    0.030534
Name: label, dtype: float64

**Ответ:** доля правильных ответов на тестовой выбрке - 96,95%.